import bcrypt from "bcryptjs";

const users = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    phoneNumber: "1234567890",
    country: "USA",
    city: "New York",
    zipCode: "10001",
    password: bcrypt.hashSync("quan1234", 10),
    isAdmin: true,
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    email: "janedoe@example.com",
    phoneNumber: "0987654321",
    country: "Canada",
    city: "Toronto",
    zipCode: "M5J 2G8",
    password: bcrypt.hashSync("quan1234", 10),
    isAdmin: false,
  },
  {
    firstName: "Bob",
    lastName: "Smith",
    email: "bobsmith@example.com",
    phoneNumber: "5555555555",
    country: "UK",
    city: "London",
    zipCode: "EC1A 1BB",
    password: bcrypt.hashSync("quan1234", 10),
    isAdmin: false,
  },
  {
    firstName: "Alice",
    lastName: "Jones",
    email: "alicejones@example.com",
    phoneNumber: "1112223333",
    country: "Australia",
    city: "Sydney",
    zipCode: "2000",
    password: bcrypt.hashSync("quan1234", 10),
    isAdmin: false,
  },
  {
    firstName: "David",
    lastName: "Lee",
    email: "davidlee@example.com",
    phoneNumber: "4445556666",
    country: "China",
    city: "Shanghai",
    zipCode: "200000",
    password: bcrypt.hashSync("quan1234", 10),
    isAdmin: false,
  },
  {
    firstName: "Maria",
    lastName: "Garcia",
    email: "mariagarcia@example.com",
    phoneNumber: "7778889999",
    country: "Spain",
    city: "Madrid",
    zipCode: "28001",
    password: bcrypt.hashSync("quan1234", 10),
    isAdmin: true,
  },
];
export default users;
